### ISSUE TITLE
how to determine the needed distance from object for vibration measurement using A121(Python)

### ISSUE THREAD

**Issue by yalatoom** [acconeer/acconeer-python-exploration#153]
How to determine the needed distance from an object for vibration measurement using A121 (python)?
what maximum distance the A121 sensor can estimate the vibration of an object?
I found that in the below URL that variable [measured_point] could handle that, but what is the unit of it?

(https://docs.acconeer.com/en/latest/example_apps/a121/vibration.html#acconeer.exptool.a121.algo.vibration._example_app.ExampleAppConfig.measured_point)

**Comment by AndersBuhl** [comment]
Hi,

measured_point is unit less since it refers to the measured radar point. The points has 2.5 mm between each other so measured_point=80 corresponds to 0.2 meters. The maximum distance will depend on the displacement of the object and also what type of object it is. Good reflectors will have a longer maximum distance.

BR,
Anders

**Comment by yalatoom** [comment]
> Hi,
> 
> measured_point is unit less since it refers to the measured radar point. The points has 2.5 mm between each other so measured_point=80 corresponds to 0.2 meters. The maximum distance will depend on the displacement of the object and also what type of object it is. Good reflectors will have a longer maximum distance.
> 
> BR, Anders

Thank you.

**Comment by yalatoom** [comment]
solved
