### ISSUE TITLE
XM112 with_cli.py example & SPI client does not save data Windows 10

### ISSUE THREAD

**Issue by jkablan** [acconeer/acconeer-python-exploration#35]
1. Create virtual environment from requirements.txt
2. Run the with_cli.py example using the spi connection (XM112)  "acconeer-python-exploration\examples\record_data>python with_cli.py --spi -o data.h5"
3. The script will connect and start recording data
4. Press ctrl-c to stop the script. Rather than catching the signal and exiting gracefully, an exception will be thrown and the data will is not written to file.

** Traceback:**
`Traceback (most recent call last):
  File "with_cli.py", line 74, in <module>
    main()
  File "with_cli.py", line 51, in main
    data_info, data = client.get_next()
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\acconeer\exptool\clients\base.py", line 82, in get_next
    return self._get_next()
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\acconeer\exptool\clients\reg\client.py", line 454, in _get_next
    ret_cmd, ret_args = self._data_queue.get()
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\queues.py", line 94, in get
    res = self._recv_bytes()
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\connection.py", line 306, in _recv_bytes
    [ov.event], False, INFINITE)
InterruptedError: [Errno 4] Interrupted function call`

**Environment :**
 - Host OS: Windows 10
 - Acconeer hardware: XM112
 - Acconeer software version: 2.1.0
 - Exploration version: branch - master, commit - fae4544

**Comment by erikmansson** [comment]
Unfortunately, this is a known issue on Windows which we've yet to figure out how to solve. The keyboard interrupt signal from ctrl-c is correctly caught but a `InterruptedError` is still raised.

Similar to this answer on SO: https://stackoverflow.com/a/26073025/12542220

If you know how many data frames you want, you could simply run the script using the `--limit-frames 123` flag. Then you don't need to use the interrupt at all.

Otherwise, what you perhaps could do as a workaround is to remove the interrupt handler here
https://github.com/acconeer/acconeer-python-exploration/blob/a5b7e7bbfabbef05b5bc7bad762d4ac59ba026ca/examples/record_data/with_cli.py#L46-L50
and wrap the loop in try-except for the KeyboardInterrupt like this:

    i = 0
    try:
        while True:
            data_info, data = client.get_next()
            recorder.sample(data_info, data)

            i += 1

            if args.limit_frames:
                print("Sampled {:>4}/{}".format(i, args.limit_frames), end="\r", flush=True)

                if i >= args.limit_frames:
                    break
            else:
                print("Sampled {:>4}".format(i), end="\r", flush=True)
    except KeyboardInterrupt:
        pass
