### ISSUE TITLE
Material classification 

### ISSUE THREAD

**Issue by roycechung** [acconeer/acconeer-python-exploration#42]
Hi,

I'm interested in building a ML material classifier like the one shown in this video. 
https://www.youtube.com/watch?v=CkCsYt1ISa8

I saw that the python doc suggested the IQ service and looking at "features extracting averages, variances, FFT, autocorrelation" for material detection. I was wondering which features (range segment, peak, averages 1D, averages 2D, amplitude ratios 1D, sparse FFT, presence sparse) in the feature configuration tab of the ML GUI would be best to experiment with? 

Thanks,
Royce

**Comment by dj-acconeer** [comment]
Hi Royce,
thank you for your interest in our sensor technology.
Since this is a more general question and not related to a bug/issue wit the Exploration Tool,
I would kindly like to ask you to contact customer support on our Freshdesk page.

https://acconeer.freshdesk.com/support/home

I will close the thicket here, but feel free to reopen, if you find a related bug or issue with the Exploration Tool itself.
