### ISSUE TITLE
Run multiple services

### ISSUE THREAD

**Issue by kangc0016** [acconeer/acconeer-python-exploration#84]
Looking at the example_multiple_service_usage.c 

> In a loop:
> Activate the envelope service
> Get the result and print it
> Deactivate the envelope service
> Activate the sparse service
> Get the result and print it
> Deactivate the sparse service
> End of loop

If the envelope service has running average factor set, will this exponential filter be reset when we deactivate the envelope service and activate this service in the next loop iteration?

also how much time does it take to create service, and how much time does it take to activate/deactivate a service?

**Comment by erikmansson** [comment]
No, the exponential filter is not reset upon activate/deactivate.

We'll get back to you with more information on your other question.

**Comment by ola1olsson** [comment]
Hi!

>also how much time does it take to create service, and how much time does it take to activate/deactivate a service?
This is dependent on what MCU you are running on. I think we have log timestamps in most of our example integrations so it should be easy to measure the time by logging before and after. I know it won't be 100% accurate but it won't take exactly the same time always since we are using malloc() and the heap implementation in newlib nano (if you are using this) doesn't allocate/deallocate in constant time.

Don't hesitate to contact us at https://acconeer.freshdesk.com/support/home If you have more questions regarding the software which is not related to exploration tool
